# Generated by Django 4.1.6 on 2023-02-18 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function_string', models.CharField(default='sin(x)', help_text='Please b', max_length=100)),
                ('left_edge', models.IntegerField(default=-10)),
                ('right_edge', models.IntegerField(default=10)),
                ('accuracy', models.IntegerField(default=3)),
                ('date_field', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
