# Generated by Django 4.1.6 on 2023-02-18 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matplotapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equations',
            name='function_string',
            field=models.CharField(default='sin(x)', max_length=100),
        ),
    ]
