# Generated by Django 4.1.6 on 2023-02-15 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesapp', '0002_alter_fileuploaded_options_fileuploaded_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileuploaded',
            name='upload',
            field=models.ImageField(upload_to='uploadedfiles/'),
        ),
    ]
